language: node_js
node_js:
- '10'
script:
- npm run build
- npm run test
deploy:
  provider: npm
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: joernb/redux-prefabs-html-meta-data
  email:
    secure: auJyF63xtdQP6ZuLnXE52Y+jfk9CjmU1IuboZFTICXsN5RLJNXL5nvCPhnuzAW/8/C9Z7IlaSE9ycFQEMD+blOI6upwsAxDj9QLC1hQHug3hpbE98sWfVL04BGaIUvUbfv+iQJQxjjJvULJxf1t8V47qWDrbmQi47Z9B1+aS8Y/BSjIpe3NxmliZUW+7zgG8jzaG1EvhOdv2BpFfW3PIf3XaOtkUQrKD4FeYn/WEI5+elNg92kdOS8j4IXAxMJVQW30udXZWwxhy9kPHA4ZlUvoA6WO79BCc9FHT/lUKbOfHqWaxtrTVbJ3ySDOaq3Xbrj7dWejBlyCWef4lWSJX7lDl6E8N5gAQP9BfOAUJIWLg5K97aV4eYPA3m93D77tKsXEsdYlj8ixJb5pl0m8qgJ4h9UaQ6EweyNafMW/oQTqXgbsdkV82/hbkPuQSxmiGZw/j/JhY/0MZBEaqfAstqZ2r418zlaGMOW3yoB2c6Mk9D+esq1Zkx6sSSPBo0aOjideEicMUuLi6lsamxMEc7neMUB0arXgbXXYuR0fDY1qvVaFY2eZe6U9u2YPiZ9o+cqbb2UCKsnFC7eFxzKewSAiyzqjxj1n2UhaMXA+wapHUknql7VpkZoUEyv29MdgcFeMOYM4yV92Q3QAGf9SKOF6dbKDCoCsJSkWtJ844GhY=
  api_key:
    secure: J3XMzuV5fYXr+iHCYz1zRL5ljAMGq9tbENmH7ob5irpBfRkQr/wpQ15fKuTup8hIvqu1A5SHpGz6/WITNTEBRGHcKjVsTeQCakHu4SPJoOiV30WxoQ+qHcJ00Npv+cRjAkdtpP/FTLmDwESqX20sSG5+AjAx96XLBuOAHlb8tG89RXs0o5hAHwXbHibnPXMdLUKU80AXgFE/78gTD8Zd5i6C4jxPTlHoedt0Swref4Fx7AfQ62uqovrWNzg1fgTduwn9vEr82QIwyQNzwIDZw4O9nURoVWcq4RyDZsanDXzTLRb0ftka3ZNWv3Iw6tHNajAoRaXmyTfhXoiypjSmUssvLncCu59zEq6+WqRCAoP7yyYait8+DqQbGfBZRCcoqOvPu1WHr495oEi0jw4eGXDwOyoBUHt++SncigzRyhy3JUfve7ftT6QYupLM3x6IIRbS5SjPR1pPzGKtY/61vZUW41rPBauVmdT81fkctfBrf1gorA1jgmW0LTQZ5IYGu+ewWEwa36Q2nuGWr1z96ekLw5Nq2n3bkTs4Zf67MipnKRs3XzHvO07OkQeQ4CvOE0+yBLZy+dorIETDj/AGC971KdMUmYm4fejqEFiWXyPOxjXUVnEF8R3VyzkkPpqokvqMmBMQIr7/EYAT8JtwkicEGxbPT0ZgVkmYP1W3eGE=
